import {UserVo} from './User.model';
import {OrderLineVo} from './OrderLine.model';
import {CityVo} from './City.model';
import {ClientVo} from './Client.model';
import {OrderStatusVo} from './OrderStatus.model';

export class CommandVo {
    public total: string;
    public regulationDate: string;
    public adress: string;
    public reference: string;
    public remarque: string;
    public orderDate: string;
    public id: string;
    public totalMax: string;
    public totalMin: string;
    public regulationDateMax: string;
    public regulationDateMin: string;
    public orderDateMax: string;
    public orderDateMin: string;
    public deliveryVo: UserVo = new UserVo();
    public validatorVo: UserVo = new UserVo();
    public adminVo: UserVo = new UserVo();
    public clientVo: ClientVo = new ClientVo();
    public orderStatusVo: OrderStatusVo = new OrderStatusVo();
    public cityVo: CityVo = new CityVo();
    public orderLinesVo: Array<OrderLineVo> = new Array<OrderLineVo>();
    public packageStatusVo: number;
    public day: number;
    public month: number;
    public totalCommandInDay: number;
    public totalInDay: number;
    public totalSalesCurrentDay: number;
    public totalConfirmedCurrentDay: number;
    public totalClosedCurrentDay: number;
    public totalCommandsSales: number;
    public totalValidator: number;
    public totalDelivery: number;
    public confirmedCommands: number;
    public totalConfirmedCommands: number;
    public returnedCommands: number;
    public closedCommands: number;
    public totalClosedCommands: number;
    public processedCommand: number;
    public totalCommandInMonth: number;
    public totalInMonth: number;
    public totalCommandsDelivred: number;
    public totalCommandsConfirmed: number;
    public totalCommandsPaid: number;
    public totalCommands: number;
}
